webapp/admin/forms.py
from flask_admin import BaseView,expose

class CustomView(BaseView):
    @expose('/')
    def index(self):
        return self.render('admin/custom.html')
    
    @expose('second_page')
    def second_page(self):
        return self.render('admin/second_page.html')

webapp/main/forms.py
from wtforms import StringField,SubmitField
from flask_wtf import Form
from wtforms.validators import Required,Length


class MessageboardForm(Form):
    content = StringField('内容',validators=[Required(),Length(max=255)])
    submit = SubmitField('提交')

webapp/myphotos/forms.py
#coding:utf-8
from flask_wtf import Form
from wtforms import FileField,TextAreaField,SubmitField
from wtforms.validators import Required,Length
from flask_pagedown.fields import PageDownField

# class CommentForm(Form):
    
#     content = StringField('内容',validators=[Required(),Length(max=255)])
#     submit = SubmitField('提交')

# class PostForm(Form):
#     title = TextField('标题',render_kw={"class": "form-control","placeholder": "标题","aria-describedby":"sizing-addon1"})
#     subtitle = TextField('小标题',render_kw={"class": "form-control","placeholder": "子标题","aria-describedby":"sizing-addon1"})
#     text = TextAreaField("内容：（使用Markdown的语法）",validators=[Required()])
#     submit = SubmitField('提交')


class PushPicForm(Form):
    photo = FileField("图片")
    simpletext  =TextAreaField('简介')
    submit = SubmitField("上传")
    
    

    
    

webapp/post/forms.py
#coding:utf-8
from flask_wtf import Form
from wtforms import ValidationError,StringField,SubmitField,TextField,TextAreaField
from wtforms.validators import Required,Length
from flask_pagedown.fields import PageDownField

class CommentForm(Form):
    
    content = StringField('内容',validators=[Required(),Length(max=255)])
    submit = SubmitField('提交')

class PostForm(Form):
    title = TextField('标题',render_kw={"class": "form-control","placeholder": "标题","aria-describedby":"sizing-addon1"})
    subtitle = TextField('小标题',render_kw={"class": "form-control","placeholder": "子标题","aria-describedby":"sizing-addon1"})
    text = TextAreaField("内容：（使用Markdown的语法）",validators=[Required()])
    submit = SubmitField('提交')




    
    

webapp/userinfo/forms.py
#coding:utf-8
from flask_wtf import Form
from wtforms import StringField,TextAreaField,SubmitField,DateField,FileField
from wtforms.validators import Required,Length


class EditMyProfile(Form):
    headimg = FileField('头像')
    name = StringField('昵称',validators=[Length(0,64)])
    location = StringField('地点',validators=[Length(0,64)])
    about_me = TextAreaField('个人简介')
    birthday = DateField('生日')
    submit = SubmitField('提交')

webapp/__init__.py
from flask import Flask,redirect,url_for
import markdown
from .extensions import bcrypt,db,loginmanager,bootstrap,mail,admin,moment,pagedown
from flaskext.markdown import Markdown
from .models import User,Post,Comment,Tag,Messageboard
from flask_uploads import config_for_set,patch_request_class
from .controller.admin import CustomView
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_name)
    config_name.init_app(app)
    db.init_app(app)
    bcrypt.init_app(app)
    loginmanager.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    admin.init_app(app)
    moment.init_app(app)
    pagedown.init_app(app)
    



    Markdown(app)
    # admin.add_view(CustomView(name='Custom'))

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    from .post import post as post_blueprint
    app.register_blueprint(post_blueprint,url_prefix = '/post')
    
    
    from .controller import controller as controller_blueprint
    app.register_blueprint(controller_blueprint)

    from .userinfo import userinfo as userinfo_blueprint
    app.register_blueprint(userinfo_blueprint,url_prefix = '/userinfo')

    from .myfeeling import myfeeling as myfeeling_blueprint
    app.register_blueprint(myfeeling_blueprint,url_prefix ='/myfeeling')


    from .myphotos import myphotos as myphotos_blueprint
    app.register_blueprint(myphotos_blueprint,url_prefix = '/myphotos')
    return app 

webapp/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)

from . import views

webapp/controller/__init__.py
from flask import Blueprint


controller = Blueprint('controller',__name__)

from . import admin

webapp/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views

webapp/main/views.py
from . import main
from flask import render_template,redirect,url_for
from webapp.models import Post,Messageboard,db
from .forms import MessageboardForm
from datetime import datetime
from flask_login import current_user
from flask import request,Response,jsonify
import os
from manage import app
@main.route('/')
def index():
    getallposts = Post.query.order_by(Post.publish_date.desc()).all()
    if len(getallposts)>4:
        getallposts=getallposts[:4]

    return render_template('index.html',backgroundpic='static/img/home-bg.jpg',getallposts = getallposts)


@main.route('/about')
def about():
    return render_template('about.html',backgroundpic = 'static/img/about-bg.jpg')


@main.route('/contact')
def contact():
    return render_template('contact.html',backgroundpic = 'static/img/contact-bg.jpg')


@main.route('/messageboard',methods=['GET','POST'])
def messageboard():
    form = MessageboardForm()
    if form.validate_on_submit():
        message = Messageboard()
        message.name = current_user.username
        message.text = form.content.data
        message.timestamp = datetime.now()
        message.user_id = current_user.id
        db.session.add(message)
        db.session.commit()
        return redirect(url_for('.messageboard'))

    messages = Messageboard.query.order_by(Messageboard.timestamp.desc()).all()
    return render_template('messageboard.html',siteheading = '留言板',form=form,messages = messages,backgroundpic = 'static/img/contact-bg.jpg')
        
@main.route('/upload/',methods=['POST'])
def upload():
    file=request.files.get('editormd-image-file')
    if not file:
        res={
            'success':0,
            'message':u'图片格式异常'
        }
    else:
        ex=os.path.splitext(file.filename)[1]
        filename=datetime.now().strftime('%Y%m%d%H%M%S')+ex
        from manage import app
        file.save(os.path.join(app.config['SAVEPIC'],filename))
        #返回
        res={
            'success':1,
            'message':u'图片上传成功',
            'url':url_for('.image',name=filename)
        }
    return jsonify(res)

#编辑器上传图片处理
@main.route('/image/<name>')
def image(name):
    with open(os.path.join(app.config['SAVEPIC'],name),'rb') as f:
        resp=Response(f.read(),mimetype="image/jpeg")
    return resp

webapp/myfeeling/__init__.py
from flask import Blueprint
myfeeling = Blueprint('myfeeling',__name__)
from . import views

webapp/myfeeling/views.py
from . import myfeeling
from webapp.models import Myfeeling
from flask import render_template,redirect,url_for
from flask import request,Response

@myfeeling.route('/')
def feeling():
    getallfeeling  = Myfeeling.query.order_by(Myfeeling.timestamp.desc()).all()
    return render_template('myfeeling/myfeeling.html',backgroundpic='/static/img/mood_bk.jpg')

webapp/myphotos/__init__.py
from flask import Blueprint
myphotos = Blueprint('myphotos',__name__)

from . import views

webapp/myphotos/views.py
from . import myphotos
from .forms import PushPicForm
from webapp.models import Post,db,Photos
from flask import render_template,current_app,flash
from flask import redirect,url_for,request
from flask_login import login_required,current_user
from datetime import datetime
from PIL import Image
import os





@myphotos.route('/',methods=['GET','POST'])
def showphotos():
    getallphotos =  Photos.query.order_by(Photos.timestamp.desc())
    return render_template('photos/photos.html',getallphotos=getallphotos,backgroundpic ='/static/img/post2_bg.jpg')



@myphotos.route('/<int:photo_id>',methods=['GET','POST'])
def showsinglephoto(photo_id):
    singlephoto = Photos.query.filter_by(id=photo_id).first()
    username=singlephoto.user.username
    return render_template('photos/photo.html',singlephoto=singlephoto,username=username,backgroundpic='/static/img/post2_bg.jpg')

def random_str(length=32):
    import random
    base_str = 'qwertyuioplkjhgfdsazcxvbnm0123456789'
    return ''.join(random.choice(base_str) for i in range(length))


@myphotos.route('/upload',methods= ['GET','POST'])
@login_required
def uploadphoto():
    form =PushPicForm()
    if form.validate_on_submit():
        photo=Photos()
        photo.timestamp=datetime.now()
        photo.user_id=current_user.id 
        photo.description = form.simpletext.data
        filename = form.photo.data.filename
        UPLOAD_PHOTOS_FOLDER = current_app.config['UPLOAD_PHOTOS_FOLDER']
        form.photo.data.save('{}{}_{}'.format(UPLOAD_PHOTOS_FOLDER,current_user.username,filename))
        photo.pic_url  ='/static/picture/{}_{}'.format(current_user.username,filename)
        db.session.add(photo)
        db.session.commit()
        flash("上传成功","ok")
        return redirect('/myphotos')       
    return render_template('photos/upphoto.html',form=form,backgroundpic='/static/img/post2_bg.jpg')

webapp/post/__init__.py
from flask import Blueprint
post = Blueprint('post',__name__)

from . import views

webapp/post/views.py
from . import post
from webapp.models import Post,db,User,Comment
from flask import render_template
from .forms import PostForm,CommentForm
from flask import redirect,url_for
from flask_login import current_user
from datetime import datetime


@post.route('/article/<int:post_id>',methods = ['GET','POST'])  #or  '/article/<int:post_id>'
def article(post_id):
    post = Post.query.filter_by(id = post_id).first()
    form = CommentForm()
    if form.validate_on_submit():
        newcomment = Comment()
        newcomment.name =current_user.name
        newcomment.text =form.content.data
        newcomment.post_id = post.id
        newcomment.user_id = current_user.id
        newcomment.date = datetime.now()
        db.session.add(newcomment)
        db.session.commit()
        return redirect(url_for('.article',post_id = post.id))
        
    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.date).all()
    
    
    if post is None:
        return redirect(url_for('.listarticle'))
    else:
        title =post.title 
        text =post.text
        publish_date=post.publish_date
        user_id = post.user_id
        user = User.query.filter_by(id = user_id).first()

        return render_template('post.html',form=form,comments=comments,text = text,username = user.username,publish_date = publish_date,siteheading = title,backgroundpic ='/static/img/post2_bg.jpg',post=post)


@post.route('/article',methods = ['GET','POST'])
def listarticle():
    getallpost = Post.query.order_by(Post.publish_date.desc()).all()
    return render_template('listpost.html',allpost=getallpost,backgroundpic = '/static/img/post-bg.jpg')



@post.route('/writearticle',methods = ['GET','POST'])
def writearticle():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(text = form.text.data,title =form.title.data,subtitle = form.subtitle.data,user = current_user._get_current_object(),publish_date = datetime.now())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('post/writearticle.html',form=form,backgroundpic = '/static/img/post-bg.jpg')


@post.route('/article/<int:post_id>/comment',methods = ['GET','POST'])
def commentarticle(post_id):
    form = CommentForm()
    post = Post.query.filter_by(id = post_id).first()
    if form.validate_on_submit():
        newcomment = Comment()
        newcomment.name =current_user.name
        newcomment.text =form.content.data
        newcomment.post_id = post.id
        newcomment.user_id = current_user.id
        newcomment.date = datetime.now()
        db.session.add(newcomment)
        db.session.commit()
        return redirect(url_for('.commentarticle',post_id = post.id))
        
    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.date).all()
    time = datetime.now()
    
    return render_template('post/commentarticle.html',time=time,form=form,post=post,comments=comments,backgroundpic = '/static/img/post-bg.jpg')




@post.route('/article/<int:post_id>/edit',methods=['GET','POST'])
def editarticle(post_id):
    post1 = Post.query.filter_by(id = post_id).first()
    form = PostForm()
    if current_user == post1.user:
        if form.validate_on_submit():
            Post.query.filter_by(id = post_id).update({
                'text':form.text.data,
                'subtitle':form.subtitle.data,
                'title':form.title.data
            })
            
            db.session.commit()
            return redirect(url_for('main.index'))
        form.text.data = post1.text
        form.title.data = post1.title
        form.subtitle.data = post1.subtitle
        return render_template('post/editarticle.html',form=form,backgroundpic = '/static/img/post-bg.jpg')
    else :
        return redirect(url_for('main.index'))

@post.route('/editormd',methods = ['GET','POST'])
def editormd():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(text = form.text.data,title =form.title.data,subtitle = form.subtitle.data,user = current_user._get_current_object(),publish_date = datetime.now())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('post/editormd.html',form=form,backgroundpic = '/static/img/post-bg.jpg')
    
            
    

webapp/userinfo/__init__.py
from flask import Blueprint
userinfo  = Blueprint('userinfo',__name__)
from . import views

webapp/userinfo/views.py
#coding:utf-8
from . import userinfo
from flask import render_template,abort,flash,redirect,url_for
from webapp.models import User
from flask_login import login_required,current_user
from .forms import EditMyProfile
from webapp.models import db
from flask import request,current_app
from werkzeug.datastructures import ImmutableMultiDict
@userinfo.route('/<username>')
def user(username):
    user = User.query.filter_by(username = username).first()
    if user is None:
        abort(404)
    return render_template('userinfo/userinfo.html',user=user,backgroundpic = '/static/img/userinfo_bg.jpg')


@userinfo.route('/editprofile',methods = ['GET','POST'])
@login_required
def edit_profile():
    form =EditMyProfile()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        current_user.birthday = form.birthday.data
        #新增头像功能
        
        if request.method == 'POST': 
            print(request)
            print(request.files)
            if request.files == ImmutableMultiDict([]):
                
                current_user.headimg = current_user.headimg
            else:
                headimg = request.files['headimg']
                print(headimg)
                fname = headimg.filename
                
                UPLOAD_FOLDER = current_app.config['UPLOAD_FOLDER']
                ALLOWED_EXTENSIONS = ['png','jpg','jpeg','gif']
                flag = '.' in fname and fname.rsplit('.',1)[1] in ALLOWED_EXTENSIONS
                if not flag :
                    flash('文件类型错误')
                    return redirect(url_for('.user',username = current_user.username))
                headimg.save('{}{}_{}'.format(UPLOAD_FOLDER,current_user.username,fname))
                current_user.headimg = '/static/headimg/{}_{}'.format(current_user.username,fname)
                
            
        



        #end
        db.session.add(current_user)
        db.session.commit()
        flash('Your profile has been updated')
        return redirect(url_for('.user',username = current_user.username))
    headimg = current_user.headimg
    form.name.data=current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    form.birthday.data = current_user.birthday
    return render_template('userinfo/edit_profile.html',form=form,headimg = headimg,backgroundpic = '/static/img/userinfo_bg.jpg')



        

webapp/templates/about.html
{% extends "base.html"%}

{% block title %}关于{% endblock%}

{% block page_content%}
    <!-- Main Content -->
    <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <p>一个红色的技术人员，一定要做到三个条件，政治要坚定，学习马克思，列宁主义武装我头脑，技术精明，精明还要精明。</p>
                    
                </div>
            </div>
        </div>
    
        <hr>


{% endblock %}

webapp/templates/base.html
{% extends "bootstrap/base.html"%}

{% block title %}主页{% endblock%}

{% block metas %}
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{% endblock %}


{% block styles %}

{% block newstyles %}

{% endblock %}

<link href="/static/css/main.css" rel="stylesheet">
<!-- Bootstrap Core CSS -->
<link href="/static/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

<!-- Additional fonts for this theme -->
<link href="/static/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

<!-- Custom styles for this theme -->
<link href="/static/css/clean-blog.min.css" rel="stylesheet">

<!-- Temporary navbar container fix until Bootstrap 4 is patched -->
<style>
.navbar-toggler {
    z-index: 1;
}

@media (max-width: 576px) {
    nav > .container {
        width: 100%;
    }
}


</style>

{% endblock%}




{% block navbar %}
<nav class="navbar fixed-top navbar-toggleable-md navbar-light" id="mainNav">
    <div class="container">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu <i class="fa fa-bars"></i>
        </button>
        <a class="navbar-brand page-scroll" href="{{url_for('main.index')}}">Hong Chuan's Blog</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{{url_for('main.index')}}">主页</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link page-scroll" href="{{ url_for('post.editormd')}}">写文章</a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{{ url_for('post.listarticle')}}">更多文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{{ url_for('myphotos.showphotos')}}">我的作品
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{{url_for('main.about')}}">关于</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{% if current_user.username %}  /userinfo/{{current_user.username}} {% else %} {{url_for('auth.login')}} {% endif%}">个人信息</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link page-scroll" href="{{url_for('main.messageboard')}}">留言板</a>
                </li>
                


                 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                 
                {% if current_user.is_authenticated%}
                <li class="nav-item"><a class="nav-link page-scroll" href="{{url_for('auth.logout')}}">登出 &nbsp;&nbsp; </a></li>
                {% else %}
                

                <li class="nav-item"><a class="nav-link page-scroll" href="{{url_for('auth.login')}}"> 登录  &nbsp;&nbsp; </a></li>
                <li class="nav-item"><a class="nav-link page-scroll" href="{{url_for('auth.register')}}"> 注册  &nbsp;&nbsp; </a></li>
                {% endif %}
            </ul>


            
                
            
        </div>
    </div>
</nav>

{% endblock %}


{% block content %}
<header class="intro-header" style="background-image: url({{backgroundpic}})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                <div class="site-heading">
                    <h1>{{siteheading}}</h1>
                    <span class="subheading">{{subheading}}</span>
                    {% block creater%} {% endblock%}
                </div>
            </div>
        </div>
        
        
        
    </div>
</header>
{% block page_content%}


{% endblock %}

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/profile.php?id=100005139079363">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://plus.google.com/u/0/109550871816185365850">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-google fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/redtecher/myblog">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; redhongc.top 2018. </p>
            </div>
        </div>
    </div>
</footer>


{% endblock %}

{% block scripts%}

{{super()}}
<!-- jQuery Version 3.1.1 -->
<script src="/static/lib/jquery/jquery.js"></script>

<!-- Tether -->
<script src="/static/lib/tether/tether.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/static/lib/bootstrap/js/bootstrap.min.js"></script>

<!-- Theme JavaScript -->
<script src="/static/js/clean-blog.min.js"></script>

{{moment.include_moment()}}
{{pagedown.include_pagedown()}}


{% block addscripts%}{% endblock%}
{% endblock%}

webapp/templates/index.html
{% extends "base.html"%}

{% block title %} 主页{% endblock %}


{% block page_content%}
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">


            {% for post in getallposts:%}
            
            <div class="post-preview">
                <a href="{{url_for('post.article',post_id = post.id)}}">
                    <h2 class="post-title">
                        {{post.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{post.subtitle}}
                    </h3>
                </a>
                <p class="post-meta">Posted by <a href="{{url_for('userinfo.user',username = post.user.username )}}">{{post.user.username}}</a> on {{post.publish_date}}</p>
            </div>
            <hr>
            {% endfor %}
            <!-- Pager -->
            <div class="clearfix">
                <a class="btn btn-secondary float-right" href="{{url_for('post.listarticle' )}}">更多文章</a>
            </div>
        </div>
    </div>
</div>

<hr>


{% endblock %}

webapp/templates/listpost.html
{% extends "base.html"%}

{% block title %}文章列表{% endblock %}




{% block page_content%}
<div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
    {% for post in allpost %}
    <div class="post-preview">
            <a href="{{url_for('post.article',post_id = post.id)}}">
                <h2 class="post-title">
                    {{post.title}}
                </h2>
                <h3 class="post-subtitle">
                    
                </h3>
            </a>
            <p class="post-meta">Posted by  <a href="#">{{post.user.username}}</a> on {{post.publish_date}}</p>
        </div>
    {% endfor %}
            </div>
        </div>
</div>
    
    

 {% endblock%}

webapp/templates/messageboard.html
{% extends "base.html"%}

{% block title %}留言板{% endblock %}


{% block page_content%}
    <div class="container">
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
            <h3>在这里 <span class="label label-default">留言吧！</span></h3>
        {% import "bootstrap/wtf.html" as wtf %}
        
        {{ wtf.quick_form(form)}}

        </div>
        </div>
        <hr><hr>
        
        
        <div class="container">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
        
        
        <ul class="posts">
        {% for message in messages %}
            <li class="post">
        <!--
                <div class="profile-thumbnail">
                    <a href="{{url_for('userinfo.user',username = message.user.username )}}">
                        <img class="img-rounded profile-thumbnail" src="{{message.user.headimg}}",height = "5",width = "5"/>
                    </a>
                </div>
               
        -->         
                    
                <div class="post-date">{{ moment(message.timestamp).fromNow(refresh=True)}}</div>
        
                
                <div class="post-author">
                    <a href="{{url_for('userinfo.user',username = message.user.username)}}">
                        {{message.user.username}}
                    </a>
                </div>
                <div class="post-body">{{message.text}}</div>
        
            </li>
            {% endfor %}
        </ul>
    
    </div>
    </div>


   


    
    
   
 {% endblock%}

 {% block newstyles %}
 <link href="/static/css/flaskystyles.css" rel="stylesheet" type="text/css">

 {% endblock %}

webapp/templates/post.html
 {% extends "base.html"%}

{% block title %}{{post.title}}{% endblock %}


{% block creater %} <span class="meta">Posted by <a href="{{url_for('userinfo.user',username=username)}}" >{{username}}</a> on {{publish_date}}</span>
{% if current_user == post.user %}
<p class="text-warning"><button type="button" class="btn btn-info" onclick="window.location.href='/post/article/{{post.id}}/edit'">修改文章</button></p>
{% endif%}
{% endblock %}



{% block page_content%}


    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                   <div class="post-body">
                        <article class="markdown-body">
                       {% if post.body_html%}
                            {{post.body_html | safe}}
                       {% else %}
                            {{ post.text}}
                       {% endif %}
                       </article>
                    
                   </div>
                </div>
            </div>
        </div>
    </article>
    <!--<button type="button" style="float:right" class="btn btn-light">编辑文章</button>-->
    
    <hr><hr>
    <div class="container">
        <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
            <h3>在这里评论 <span class="label label-default"></span></h3>
        {% import "bootstrap/wtf.html" as wtf %}
        
        {{ wtf.quick_form(form)}}

        </div>
        </div>
        <hr><hr>
        
        
        <div class="container">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
        
        
        <ul class="posts">
        {% for comment in comments %}
            <li class="post">
        <!--
                <div class="profile-thumbnail">
                    <a href="{{url_for('userinfo.user',username = comment.user.username )}}">
                        <img class="img-rounded profile-thumbnail" src="{{comment.user.headimg}}",height = "5",width = "5"/>
                    </a>
                </div>
               
        -->         
                    
                <div class="post-date">{{ moment(comment.date).fromNow(refresh=True)}}</div>
        
                
                <div class="post-author">
                    <a href="{{url_for('userinfo.user',username = comment.user.username)}}">
                        {{comment.user.username}}
                    </a>
                </div>
                <div class="post-body">{{comment.text}}</div>
        
            </li>
            {% endfor %}
        </ul>
    
    </div>
    </div>


   


    
    
   
 {% endblock%}

 {% block newstyles %}
 <link href="/static/css/flaskystyles.css" rel="stylesheet" type="text/css">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="/static/css/github-markdown.css">
 <style>
     .markdown-body {
         box-sizing: border-box;
         min-width: 200px;
         max-width: 980px;
         margin: 0 auto;
         padding: 45px;
     }
 
     @media (max-width: 767px) {
         .markdown-body {
             padding: 15px;
         }
     }
 </style>
 {% endblock %}